DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USER;

CREATE TABLE PRODUCT(
        ID INT PRIMARY KEY,
        MANUFACTURER_NAME VARCHAR(50),
        MODEL_NAME VARCHAR(50),
        PRICE DECIMAL,
        QUANTITY INT
);

CREATE TABLE USER(
         ID INT PRIMARY KEY,
         LOGIN VARCHAR(50),
         PASSWORD VARCHAR(50),
         ROLE VARCHAR(10)
);
